//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FKRService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FKRService.IService")]
    public interface IService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertHousekeeperReport", ReplyAction="http://tempuri.org/IService/InsertHousekeeperReportResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FKRService.InsertHousekeeperReportResponce> InsertHousekeeperReportAsync(FKRService.HousekeeperReportProxy report, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertBuildControlReport", ReplyAction="http://tempuri.org/IService/InsertBuildControlReportResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FKRService.InsertBuildControlReportResponce> InsertBuildControlReportAsync(FKRService.BuildControlReportProxy report, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetHousekeeperReport", ReplyAction="http://tempuri.org/IService/GetHousekeeperReportResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FKRService.GetHousekeeperReportResponce> GetHousekeeperReportAsync(string Login, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CheckBuildControlUser", ReplyAction="http://tempuri.org/IService/CheckBuildControlUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FKRService.CheckBuildControlUserResponce> CheckBuildControlUserAsync(string Login, string PasswordHash, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetBuildControlObjects", ReplyAction="http://tempuri.org/IService/GetBuildControlObjectsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FKRService.GetBuildControlObjectsResponce> GetBuildControlObjectsAsync(long userId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetBuildControlObject", ReplyAction="http://tempuri.org/IService/GetBuildControlObjectResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FKRService.GetBuildControlObjectResponce> GetBuildControlObjectAsync(long objectId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetBuildControlReportList", ReplyAction="http://tempuri.org/IService/GetBuildControlReportListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FKRService.GetBuildControlReportListResponce> GetBuildControlReportListAsync(long objectId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCrObjectReport", ReplyAction="http://tempuri.org/IService/GetCrObjectReportResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FKRService.GetHousekeeperReportResponce> GetCrObjectReportAsync(long crId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetObjectsCRMobile", ReplyAction="http://tempuri.org/IService/GetObjectsCRMobileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FKRService.ObjectCRMobileResponce> GetObjectsCRMobileAsync(long RealityId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDpkrWork", ReplyAction="http://tempuri.org/IService/GetDpkrWorkResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FKRService.GetDpkrWorkResponse> GetDpkrWorkAsync(string municipalityId, string housesId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/KRContracts", ReplyAction="http://tempuri.org/IService/KRContractsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FKRService.KRInfoResponse> KRContractsAsync(string houseId, string houseofRegoperator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetHousesKr", ReplyAction="http://tempuri.org/IService/GetHousesKrResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FKRService.GetHousesKrResponse> GetHousesKrAsync(string programId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetProgKr", ReplyAction="http://tempuri.org/IService/GetProgKrResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FKRService.GetProgKrResponse> GetProgKrAsync(string houseId, string usedInExport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/KRInfo", ReplyAction="http://tempuri.org/IService/KRInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FKRService.KRInfoResponse> KRInfoAsync(string houseId, string houseofRegoperator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCrDocuments", ReplyAction="http://tempuri.org/IService/GetCrDocumentsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<FKRService.CrDocumentsResponse> GetCrDocumentsAsync(string houseId, string programId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HousekeeperReportProxy
    {
        
        private string housekeeperLoginField;
        
        private long objectCRField;
        
        private System.DateTime reportDateField;
        
        private string reportNumberField;
        
        private string descriptionField;
        
        private string stateField;
        
        private string checkDateField;
        
        private string checkTimeField;
        
        private string answerField;
        
        private bool isArrangedField;
        
        private ReportFile[] reportFilesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string HousekeeperLogin
        {
            get
            {
                return this.housekeeperLoginField;
            }
            set
            {
                this.housekeeperLoginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long ObjectCR
        {
            get
            {
                return this.objectCRField;
            }
            set
            {
                this.objectCRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ReportDate
        {
            get
            {
                return this.reportDateField;
            }
            set
            {
                this.reportDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ReportNumber
        {
            get
            {
                return this.reportNumberField;
            }
            set
            {
                this.reportNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CheckDate
        {
            get
            {
                return this.checkDateField;
            }
            set
            {
                this.checkDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CheckTime
        {
            get
            {
                return this.checkTimeField;
            }
            set
            {
                this.checkTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Answer
        {
            get
            {
                return this.answerField;
            }
            set
            {
                this.answerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool IsArranged
        {
            get
            {
                return this.isArrangedField;
            }
            set
            {
                this.isArrangedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReportFiles", Order=10)]
        public ReportFile[] ReportFiles
        {
            get
            {
                return this.reportFilesField;
            }
            set
            {
                this.reportFilesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReportFile
    {
        
        private string fileNameField;
        
        private string descriptionField;
        
        private string base64Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Base64
        {
            get
            {
                return this.base64Field;
            }
            set
            {
                this.base64Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Document
    {
        
        private long documentIdField;
        
        private long typeWorkCrIdField;
        
        private string documentNameField;
        
        private long idField;
        
        private string fileField;
        
        private string nameField;
        
        private string extentionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long DocumentId
        {
            get
            {
                return this.documentIdField;
            }
            set
            {
                this.documentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long TypeWorkCrId
        {
            get
            {
                return this.typeWorkCrIdField;
            }
            set
            {
                this.typeWorkCrIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DocumentName
        {
            get
            {
                return this.documentNameField;
            }
            set
            {
                this.documentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string File
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Extention
        {
            get
            {
                return this.extentionField;
            }
            set
            {
                this.extentionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Section
    {
        
        private long idField;
        
        private string nameField;
        
        private Document[] documentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Documents", Order=2)]
        public Document[] Documents
        {
            get
            {
                return this.documentsField;
            }
            set
            {
                this.documentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CrDocumentsResponse
    {
        
        private Section[] sectionsField;
        
        private Result resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sections", Order=0)]
        public Section[] Sections
        {
            get
            {
                return this.sectionsField;
            }
            set
            {
                this.sectionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Result Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Result
    {
        
        private string codeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProgKrResponse
    {
        
        private ProgKr[] progKrField;
        
        private Result resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProgKr", Order=0)]
        public ProgKr[] ProgKr
        {
            get
            {
                return this.progKrField;
            }
            set
            {
                this.progKrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Result Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProgKr
    {
        
        private HouseKr[] houseKrField;
        
        private long idField;
        
        private string nameField;
        
        private string periodField;
        
        private string startDateField;
        
        private string finishDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HouseKr", Order=0)]
        public HouseKr[] HouseKr
        {
            get
            {
                return this.houseKrField;
            }
            set
            {
                this.houseKrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Period
        {
            get
            {
                return this.periodField;
            }
            set
            {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FinishDate
        {
            get
            {
                return this.finishDateField;
            }
            set
            {
                this.finishDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HouseKr
    {
        
        private long idField;
        
        private string muField;
        
        private string addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Mu
        {
            get
            {
                return this.muField;
            }
            set
            {
                this.muField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHousesKrResponse
    {
        
        private ProgKr progKrField;
        
        private Result resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ProgKr ProgKr
        {
            get
            {
                return this.progKrField;
            }
            set
            {
                this.progKrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Result Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FundingSources
    {
        
        private long idField;
        
        private long financeSourceIdField;
        
        private string nameField;
        
        private long idWorkField;
        
        private string typeWorkField;
        
        private int yearField;
        
        private decimal budgetMuField;
        
        private decimal budgetSubjectField;
        
        private decimal ownerResourceField;
        
        private decimal fundResourceField;
        
        private decimal otherSourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long FinanceSourceId
        {
            get
            {
                return this.financeSourceIdField;
            }
            set
            {
                this.financeSourceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long IdWork
        {
            get
            {
                return this.idWorkField;
            }
            set
            {
                this.idWorkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeWork
        {
            get
            {
                return this.typeWorkField;
            }
            set
            {
                this.typeWorkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Year
        {
            get
            {
                return this.yearField;
            }
            set
            {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal BudgetMu
        {
            get
            {
                return this.budgetMuField;
            }
            set
            {
                this.budgetMuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal BudgetSubject
        {
            get
            {
                return this.budgetSubjectField;
            }
            set
            {
                this.budgetSubjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal OwnerResource
        {
            get
            {
                return this.ownerResourceField;
            }
            set
            {
                this.ownerResourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal FundResource
        {
            get
            {
                return this.fundResourceField;
            }
            set
            {
                this.fundResourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal OtherSource
        {
            get
            {
                return this.otherSourceField;
            }
            set
            {
                this.otherSourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ContractorWork
    {
        
        private long idField;
        
        private decimal sumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Sum
        {
            get
            {
                return this.sumField;
            }
            set
            {
                this.sumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ContractorOrg
    {
        
        private ContractorWork[] contractorWorkField;
        
        private long idDocField;
        
        private long idField;
        
        private string contractorField;
        
        private string legalAddressField;
        
        private string nameBossField;
        
        private string contactBossField;
        
        private string docNameField;
        
        private string docNumField;
        
        private string dateDocField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public ContractorWork[] ContractorWork
        {
            get
            {
                return this.contractorWorkField;
            }
            set
            {
                this.contractorWorkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long IdDoc
        {
            get
            {
                return this.idDocField;
            }
            set
            {
                this.idDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Contractor
        {
            get
            {
                return this.contractorField;
            }
            set
            {
                this.contractorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LegalAddress
        {
            get
            {
                return this.legalAddressField;
            }
            set
            {
                this.legalAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameBoss
        {
            get
            {
                return this.nameBossField;
            }
            set
            {
                this.nameBossField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ContactBoss
        {
            get
            {
                return this.contactBossField;
            }
            set
            {
                this.contactBossField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DocName
        {
            get
            {
                return this.docNameField;
            }
            set
            {
                this.docNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DocNum
        {
            get
            {
                return this.docNumField;
            }
            set
            {
                this.docNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DateDoc
        {
            get
            {
                return this.dateDocField;
            }
            set
            {
                this.dateDocField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Contractor
    {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class File
    {
        
        private long idField;
        
        private string nameField;
        
        private string base64Field;
        
        private string extentionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Base64
        {
            get
            {
                return this.base64Field;
            }
            set
            {
                this.base64Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Extention
        {
            get
            {
                return this.extentionField;
            }
            set
            {
                this.extentionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WorkAct
    {
        
        private File appField;
        
        private long idField;
        
        private string numberField;
        
        private System.DateTime dateField;
        
        private decimal sumField;
        
        private decimal volumeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public File App
        {
            get
            {
                return this.appField;
            }
            set
            {
                this.appField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Sum
        {
            get
            {
                return this.sumField;
            }
            set
            {
                this.sumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Volume
        {
            get
            {
                return this.volumeField;
            }
            set
            {
                this.volumeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Photo
    {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Work
    {
        
        private Photo[] photoArchiveField;
        
        private WorkAct[] workActsField;
        
        private Contractor[] contractorsField;
        
        private long idWorkField;
        
        private string nameField;
        
        private string measureField;
        
        private string planYearField;
        
        private decimal planSumField;
        
        private decimal planVolumeField;
        
        private string startDateField;
        
        private string finishDateField;
        
        private decimal percentField;
        
        private decimal sumField;
        
        private decimal volumeField;
        
        private decimal factVolumeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Photo[] PhotoArchive
        {
            get
            {
                return this.photoArchiveField;
            }
            set
            {
                this.photoArchiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public WorkAct[] WorkActs
        {
            get
            {
                return this.workActsField;
            }
            set
            {
                this.workActsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Contractor[] Contractors
        {
            get
            {
                return this.contractorsField;
            }
            set
            {
                this.contractorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long IdWork
        {
            get
            {
                return this.idWorkField;
            }
            set
            {
                this.idWorkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Measure
        {
            get
            {
                return this.measureField;
            }
            set
            {
                this.measureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PlanYear
        {
            get
            {
                return this.planYearField;
            }
            set
            {
                this.planYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PlanSum
        {
            get
            {
                return this.planSumField;
            }
            set
            {
                this.planSumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PlanVolume
        {
            get
            {
                return this.planVolumeField;
            }
            set
            {
                this.planVolumeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FinishDate
        {
            get
            {
                return this.finishDateField;
            }
            set
            {
                this.finishDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Percent
        {
            get
            {
                return this.percentField;
            }
            set
            {
                this.percentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Sum
        {
            get
            {
                return this.sumField;
            }
            set
            {
                this.sumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Volume
        {
            get
            {
                return this.volumeField;
            }
            set
            {
                this.volumeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal FactVolume
        {
            get
            {
                return this.factVolumeField;
            }
            set
            {
                this.factVolumeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ProgramKR
    {
        
        private Work[] worksField;
        
        private ContractorOrg[] contractorOrgsField;
        
        private FundingSources[] fundingSourcesField;
        
        private long idProgField;
        
        private string nameProgField;
        
        private int yearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Work[] Works
        {
            get
            {
                return this.worksField;
            }
            set
            {
                this.worksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public ContractorOrg[] ContractorOrgs
        {
            get
            {
                return this.contractorOrgsField;
            }
            set
            {
                this.contractorOrgsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public FundingSources[] FundingSources
        {
            get
            {
                return this.fundingSourcesField;
            }
            set
            {
                this.fundingSourcesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long IdProg
        {
            get
            {
                return this.idProgField;
            }
            set
            {
                this.idProgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NameProg
        {
            get
            {
                return this.nameProgField;
            }
            set
            {
                this.nameProgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Year
        {
            get
            {
                return this.yearField;
            }
            set
            {
                this.yearField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KRInfoResponse
    {
        
        private ProgramKR[] programsKRField;
        
        private Result resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public ProgramKR[] ProgramsKR
        {
            get
            {
                return this.programsKRField;
            }
            set
            {
                this.programsKRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Result Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DPKR
    {
        
        private long commonEstateObjectsField;
        
        private string commonEstateObjectField;
        
        private long yearField;
        
        private long correctYearField;
        
        private decimal sumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long CommonEstateObjects
        {
            get
            {
                return this.commonEstateObjectsField;
            }
            set
            {
                this.commonEstateObjectsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CommonEstateObject
        {
            get
            {
                return this.commonEstateObjectField;
            }
            set
            {
                this.commonEstateObjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long Year
        {
            get
            {
                return this.yearField;
            }
            set
            {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long CorrectYear
        {
            get
            {
                return this.correctYearField;
            }
            set
            {
                this.correctYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal Sum
        {
            get
            {
                return this.sumField;
            }
            set
            {
                this.sumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDpkrWorkResponse
    {
        
        private DPKR[] dPKRField;
        
        private Result resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DPKR", Order=0)]
        public DPKR[] DPKR
        {
            get
            {
                return this.dPKRField;
            }
            set
            {
                this.dPKRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Result Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CRObjectWork
    {
        
        private long workIdField;
        
        private string workNameField;
        
        private string contractNumberField;
        
        private string contractStateField;
        
        private System.DateTime dateFromField;
        
        private System.DateTime dateToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long WorkId
        {
            get
            {
                return this.workIdField;
            }
            set
            {
                this.workIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string WorkName
        {
            get
            {
                return this.workNameField;
            }
            set
            {
                this.workNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ContractNumber
        {
            get
            {
                return this.contractNumberField;
            }
            set
            {
                this.contractNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ContractState
        {
            get
            {
                return this.contractStateField;
            }
            set
            {
                this.contractStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime DateFrom
        {
            get
            {
                return this.dateFromField;
            }
            set
            {
                this.dateFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime DateTo
        {
            get
            {
                return this.dateToField;
            }
            set
            {
                this.dateToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectCRMobile
    {
        
        private long objectIdField;
        
        private string programNameField;
        
        private string periodField;
        
        private CRObjectWork[] worksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ObjectId
        {
            get
            {
                return this.objectIdField;
            }
            set
            {
                this.objectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ProgramName
        {
            get
            {
                return this.programNameField;
            }
            set
            {
                this.programNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Period
        {
            get
            {
                return this.periodField;
            }
            set
            {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Works", Order=3)]
        public CRObjectWork[] Works
        {
            get
            {
                return this.worksField;
            }
            set
            {
                this.worksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjectCRMobileResponce
    {
        
        private ObjectCRMobile[] objectsCRMobileField;
        
        private Result resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ObjectsCRMobile", Order=0)]
        public ObjectCRMobile[] ObjectsCRMobile
        {
            get
            {
                return this.objectsCRMobileField;
            }
            set
            {
                this.objectsCRMobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Result Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BuildControlReportListItemProxy
    {
        
        private long idField;
        
        private string objectCRField;
        
        private string stageIdField;
        
        private string workNameField;
        
        private string contragentSMRField;
        
        private string contragentSKField;
        
        private bool deadlineMissedField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ObjectCR
        {
            get
            {
                return this.objectCRField;
            }
            set
            {
                this.objectCRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StageId
        {
            get
            {
                return this.stageIdField;
            }
            set
            {
                this.stageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string WorkName
        {
            get
            {
                return this.workNameField;
            }
            set
            {
                this.workNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ContragentSMR
        {
            get
            {
                return this.contragentSMRField;
            }
            set
            {
                this.contragentSMRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ContragentSK
        {
            get
            {
                return this.contragentSKField;
            }
            set
            {
                this.contragentSKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool DeadlineMissed
        {
            get
            {
                return this.deadlineMissedField;
            }
            set
            {
                this.deadlineMissedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBuildControlReportListResponce
    {
        
        private BuildControlReportListItemProxy[] buildControlReportListField;
        
        private Result resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(" BuildControlReportList", Order=0)]
        public BuildControlReportListItemProxy[] BuildControlReportList
        {
            get
            {
                return this.buildControlReportListField;
            }
            set
            {
                this.buildControlReportListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Result Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBuildControlObjectResponce
    {
        
        private BuildControlObjectCR buildControlObjectCRField;
        
        private Result resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BuildControlObjectCR BuildControlObjectCR
        {
            get
            {
                return this.buildControlObjectCRField;
            }
            set
            {
                this.buildControlObjectCRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Result Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BuildControlObjectCR
    {
        
        private long objectIdField;
        
        private string addressField;
        
        private string programNameField;
        
        private string periodField;
        
        private CRObjectWorkSmr[] worksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ObjectId
        {
            get
            {
                return this.objectIdField;
            }
            set
            {
                this.objectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ProgramName
        {
            get
            {
                return this.programNameField;
            }
            set
            {
                this.programNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Period
        {
            get
            {
                return this.periodField;
            }
            set
            {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Works", Order=4)]
        public CRObjectWorkSmr[] Works
        {
            get
            {
                return this.worksField;
            }
            set
            {
                this.worksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CRObjectWorkSmr
    {
        
        private long workIdField;
        
        private string workNameField;
        
        private long contragentIdField;
        
        private string contragentNameField;
        
        private string contractNumberField;
        
        private string contractStateField;
        
        private System.DateTime dateFromField;
        
        private System.DateTime dateToField;
        
        private CRObjectWorkStage[] workStagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long WorkId
        {
            get
            {
                return this.workIdField;
            }
            set
            {
                this.workIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string WorkName
        {
            get
            {
                return this.workNameField;
            }
            set
            {
                this.workNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long ContragentId
        {
            get
            {
                return this.contragentIdField;
            }
            set
            {
                this.contragentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ContragentName
        {
            get
            {
                return this.contragentNameField;
            }
            set
            {
                this.contragentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ContractNumber
        {
            get
            {
                return this.contractNumberField;
            }
            set
            {
                this.contractNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ContractState
        {
            get
            {
                return this.contractStateField;
            }
            set
            {
                this.contractStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime DateFrom
        {
            get
            {
                return this.dateFromField;
            }
            set
            {
                this.dateFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime DateTo
        {
            get
            {
                return this.dateToField;
            }
            set
            {
                this.dateToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WorkStages", Order=8)]
        public CRObjectWorkStage[] WorkStages
        {
            get
            {
                return this.workStagesField;
            }
            set
            {
                this.workStagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CRObjectWorkStage
    {
        
        private long workIdField;
        
        private long stageIdField;
        
        private string stageNameField;
        
        private System.DateTime dateStartWorkField;
        
        private System.DateTime dateEndWorkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long WorkId
        {
            get
            {
                return this.workIdField;
            }
            set
            {
                this.workIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long StageId
        {
            get
            {
                return this.stageIdField;
            }
            set
            {
                this.stageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StageName
        {
            get
            {
                return this.stageNameField;
            }
            set
            {
                this.stageNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime DateStartWork
        {
            get
            {
                return this.dateStartWorkField;
            }
            set
            {
                this.dateStartWorkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime DateEndWork
        {
            get
            {
                return this.dateEndWorkField;
            }
            set
            {
                this.dateEndWorkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBuildControlObjectsResponce
    {
        
        private BuildControlObjectCR[] objectsField;
        
        private Result resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Objects", Order=0)]
        public BuildControlObjectCR[] Objects
        {
            get
            {
                return this.objectsField;
            }
            set
            {
                this.objectsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Result Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckBuildControlUserResponce
    {
        
        private long userIdField;
        
        private long contragentIdField;
        
        private Result resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long ContragentId
        {
            get
            {
                return this.contragentIdField;
            }
            set
            {
                this.contragentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Result Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetHousekeeperReportResponce
    {
        
        private HousekeeperReportProxy[] housekeeperReportsField;
        
        private Result resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HousekeeperReports", Order=0)]
        public HousekeeperReportProxy[] HousekeeperReports
        {
            get
            {
                return this.housekeeperReportsField;
            }
            set
            {
                this.housekeeperReportsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Result Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertBuildControlReportResponce
    {
        
        private Result resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Result Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BuildControlReportProxy
    {
        
        private long idField;
        
        private long objectCRIdField;
        
        private long stageIdField;
        
        private decimal percentOfCompletionField;
        
        private decimal latitudeField;
        
        private decimal longitudeField;
        
        private long workIdField;
        
        private long contragentSMRIdField;
        
        private long contragentSKIdField;
        
        private bool deadlineMissedField;
        
        private string descriptionField;
        
        private ReportFile[] reportFilesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long ObjectCRId
        {
            get
            {
                return this.objectCRIdField;
            }
            set
            {
                this.objectCRIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long StageId
        {
            get
            {
                return this.stageIdField;
            }
            set
            {
                this.stageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal PercentOfCompletion
        {
            get
            {
                return this.percentOfCompletionField;
            }
            set
            {
                this.percentOfCompletionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal Latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal Longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long WorkId
        {
            get
            {
                return this.workIdField;
            }
            set
            {
                this.workIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long ContragentSMRId
        {
            get
            {
                return this.contragentSMRIdField;
            }
            set
            {
                this.contragentSMRIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long ContragentSKId
        {
            get
            {
                return this.contragentSKIdField;
            }
            set
            {
                this.contragentSKIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool DeadlineMissed
        {
            get
            {
                return this.deadlineMissedField;
            }
            set
            {
                this.deadlineMissedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReportFiles", Order=11)]
        public ReportFile[] ReportFiles
        {
            get
            {
                return this.reportFilesField;
            }
            set
            {
                this.reportFilesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertHousekeeperReportResponce
    {
        
        private Result resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Result Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServiceChannel : FKRService.IService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<FKRService.IService>, FKRService.IService
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<FKRService.InsertHousekeeperReportResponce> InsertHousekeeperReportAsync(FKRService.HousekeeperReportProxy report, string token)
        {
            return base.Channel.InsertHousekeeperReportAsync(report, token);
        }
        
        public System.Threading.Tasks.Task<FKRService.InsertBuildControlReportResponce> InsertBuildControlReportAsync(FKRService.BuildControlReportProxy report, string token)
        {
            return base.Channel.InsertBuildControlReportAsync(report, token);
        }
        
        public System.Threading.Tasks.Task<FKRService.GetHousekeeperReportResponce> GetHousekeeperReportAsync(string Login, string token)
        {
            return base.Channel.GetHousekeeperReportAsync(Login, token);
        }
        
        public System.Threading.Tasks.Task<FKRService.CheckBuildControlUserResponce> CheckBuildControlUserAsync(string Login, string PasswordHash, string token)
        {
            return base.Channel.CheckBuildControlUserAsync(Login, PasswordHash, token);
        }
        
        public System.Threading.Tasks.Task<FKRService.GetBuildControlObjectsResponce> GetBuildControlObjectsAsync(long userId, string token)
        {
            return base.Channel.GetBuildControlObjectsAsync(userId, token);
        }
        
        public System.Threading.Tasks.Task<FKRService.GetBuildControlObjectResponce> GetBuildControlObjectAsync(long objectId, string token)
        {
            return base.Channel.GetBuildControlObjectAsync(objectId, token);
        }
        
        public System.Threading.Tasks.Task<FKRService.GetBuildControlReportListResponce> GetBuildControlReportListAsync(long objectId, string token)
        {
            return base.Channel.GetBuildControlReportListAsync(objectId, token);
        }
        
        public System.Threading.Tasks.Task<FKRService.GetHousekeeperReportResponce> GetCrObjectReportAsync(long crId, string token)
        {
            return base.Channel.GetCrObjectReportAsync(crId, token);
        }
        
        public System.Threading.Tasks.Task<FKRService.ObjectCRMobileResponce> GetObjectsCRMobileAsync(long RealityId, string token)
        {
            return base.Channel.GetObjectsCRMobileAsync(RealityId, token);
        }
        
        public System.Threading.Tasks.Task<FKRService.GetDpkrWorkResponse> GetDpkrWorkAsync(string municipalityId, string housesId)
        {
            return base.Channel.GetDpkrWorkAsync(municipalityId, housesId);
        }
        
        public System.Threading.Tasks.Task<FKRService.KRInfoResponse> KRContractsAsync(string houseId, string houseofRegoperator)
        {
            return base.Channel.KRContractsAsync(houseId, houseofRegoperator);
        }
        
        public System.Threading.Tasks.Task<FKRService.GetHousesKrResponse> GetHousesKrAsync(string programId)
        {
            return base.Channel.GetHousesKrAsync(programId);
        }
        
        public System.Threading.Tasks.Task<FKRService.GetProgKrResponse> GetProgKrAsync(string houseId, string usedInExport)
        {
            return base.Channel.GetProgKrAsync(houseId, usedInExport);
        }
        
        public System.Threading.Tasks.Task<FKRService.KRInfoResponse> KRInfoAsync(string houseId, string houseofRegoperator)
        {
            return base.Channel.KRInfoAsync(houseId, houseofRegoperator);
        }
        
        public System.Threading.Tasks.Task<FKRService.CrDocumentsResponse> GetCrDocumentsAsync(string houseId, string programId)
        {
            return base.Channel.GetCrDocumentsAsync(houseId, programId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                return new System.ServiceModel.EndpointAddress("http://kapremont.samregion.ru/mingkh/ws/CrService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IService))
            {
                return new System.ServiceModel.EndpointAddress("https://kapremont.samregion.ru/mingkh/ws/CrService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService,
            
            BasicHttpsBinding_IService,
        }
    }
}
